test_that("core extractor methods return the expected types", {
  fit <- fit_test_model(interaction = TRUE, q = 4)
  expect_type(coef(fit), "double")
  expect_true(is.matrix(vcov(fit)))
  expect_true(is.matrix(confint(fit)))
  expect_type(residuals(fit), "double")
  expect_s3_class(formula(fit), "formula")
  expect_equal(nobs(fit), fit$data_info$n_used)
  expect_type(df.residual(fit), "double")
})

test_that("extractor methods agree with stored results", {
  fit <- fit_test_model(interaction = TRUE, q = 4)
  expect_equal(coef(fit), fit$results$coefficients)
  expect_equal(vcov(fit), fit$results$vcov)
  expect_equal(residuals(fit), stats::residuals(fit$fits$outcome_fit))
  expect_equal(nobs(fit), fit$data_info$n_used)
  expect_equal(df.residual(fit), nobs(fit) - length(coef(fit)))
})

test_that("coefficient, covariance, and confidence interval outputs are aligned", {
  fit <- fit_test_model(interaction = TRUE, q = 4)
  coef_names <- names(coef(fit))
  vc <- vcov(fit)
  ci <- confint(fit)
  expect_identical(coef_names, rownames(vc))
  expect_identical(coef_names, colnames(vc))
  expect_identical(coef_names, rownames(ci))
  expect_identical(colnames(ci), c("2.5 %", "97.5 %"))
})

test_that("confidence interval subsetting works by name and position", {
  fit <- fit_test_model(interaction = TRUE, q = 4)
  ci_name <- confint(fit, parm = "psi1")
  ci_pos <- confint(fit, parm = 2)
  expect_true(is.matrix(ci_name))
  expect_true(is.matrix(ci_pos))
  expect_identical(rownames(ci_name), "psi1")
  expect_identical(rownames(ci_pos), "psi1")
  expect_equal(ci_name, ci_pos)
})

test_that("confidence interval validation catches bad inputs", {
  fit <- fit_test_model(interaction = TRUE, q = 4)
  expect_error(confint(fit, parm = "not_a_parameter"))
  expect_error(confint(fit, parm = 99))
  expect_error(confint(fit, level = 1))
  expect_error(confint(fit, level = 0))
  expect_error(confint(fit, level = NA_real_))
})
